name: weather_forecast
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dio: ^5.3.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get: ^4.6.5
  http: ^1.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
