name: weather_forecast
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get: ^4.6.5
  http: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
